"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.military = void 0;
var inversify_1 = require("inversify");
var types_1 = require("../types");
var entities_1 = require("./entities");
var military = new inversify_1.Container();
exports.military = military;
military.bind(types_1.TYPES.Warrior).to(entities_1.Bogatyr);
military.bind(types_1.TYPES.Weapon).to(entities_1.Mace);
military.bind(types_1.TYPES.ThrowableWeapon).to(entities_1.Gantlet);
